app/Http/routes.php
<?php

Route::post('exam/codeExec', function(){

    return \Execute::run(Request::get('lang'));
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::post("code/submit", "ExamController@saveResult");

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
Route::resource('questions','QuestionsController');
Route::resource('questions.testcases','TestsCasesController');
Route::resource('exam','ExamController');

app/Question.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model {

    protected $fillable = ['title', 'body','language','created_by','note','exam_code'];

    public function setExamCodeAttribute($value)
    {
        $this->attributes['exam_code'] = $this->genExamCode();
    }

    public function testCases()
    {
        return $this->hasMany('App\TestCase');
    }

    public function  genExamCode(){


        $examCode = bin2hex(openssl_random_pseudo_bytes(3));

        if(Question::where('exam_code', $examCode)->first()){
            $this->genExamCode();
        }else{
            return $examCode;
        }
    }
}

app/Http/Controllers/QuestionsController.php
<?php namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateQuestion;
use App\Question;
use Illuminate\Support\Facades\Input;

class QuestionsController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('questions.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateQuestion $request)
	{

		Question::create($request->all());

		\Flash::success('Question Created Successfully');
		return redirect('/home');

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		dd("show");
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		dd("edit");

	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		dd("update");
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		dd("destroy");

	}

}

resources/views/questions/create.blade.php
@extends('app')

@section('content')
    <div class="page-title">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h3>Create New Question</h3>
                </div>
                <div class="col-md-6">
                    <a href="{{ route('questions.create') }}" style="margin-top: 10px;" class="pull-right btn btn-primary btn-lg "><i class="fa fa-times"></i>Cancel and Go back</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


            <form class="form-horizontal" role="form" method="POST" action="{{ route('questions.store') }}">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label class="col-md-4 control-label">Title :</label>
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="title" value="{{ old('title') }}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Body (Actual Question ) :</label>
                    <div class="col-md-6">
                        <textarea name="body" class="form-control" rows="8">{{ old('body') }}</textarea>
                    </div>
                </div>



                <div class="form-group">
                    <label class="col-md-4 control-label">Choose Language :</label>
                    <div class="col-md-6">
                        <select name="language" id="language" class="form-control">
                            <option value="c">C</option>
                            <option value="c++">C++</option>
                            <option value="java">Java</option>
                            <option value="php">Php</option>
                            <option value="python">Python</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Any Note's ? ( Optional ):</label>
                    <div class="col-md-6">
                        <textarea name="note" class="form-control" rows="2">{{ old('notes') }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <input type="hidden" name="created_by" value="{{ Auth::user()->id }}"/>
                        <input type="hidden" name="exam_code" value="{{ Auth::user()->id }}"/>
                        <button type="submit" class="btn btn-lg btn-primary">Create New Question</button>

                        <button type="reset" class="btn btn-link">Clear</button>
                    </div>
                </div>
            </form>
    </div>
@endsection